<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerYpjfxhp\appProdProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerYpjfxhp/appProdProjectContainer.php') {
    touch(__DIR__.'/ContainerYpjfxhp.legacy');

    return;
}

if (!\class_exists(appProdProjectContainer::class, false)) {
    \class_alias(\ContainerYpjfxhp\appProdProjectContainer::class, appProdProjectContainer::class, false);
}

return new \ContainerYpjfxhp\appProdProjectContainer(array(
    'container.build_hash' => 'Ypjfxhp',
    'container.build_id' => '50a0040f',
    'container.build_time' => 1734178773,
), __DIR__.\DIRECTORY_SEPARATOR.'ContainerYpjfxhp');
